# pull official base image
FROM node:18.17.1-alpine

# set working directory
WORKDIR /app

# install app dependencies
COPY package.json /app
COPY package-lock.json /app
RUN npm install --silent

# add app
COPY . /app

EXPOSE 3000

# start app
CMD ["npm", "start"]
