ARG RUST_VERSION=1.72.0
ARG APP_NAME=consumer
FROM rust:${RUST_VERSION}-slim-bullseye AS build
ARG APP_NAME
WORKDIR /app

# dependencies to compile the Kafka client
RUN apt-get update && apt-get install -y build-essential \
  curl \
  openssl libssl-dev \
  pkg-config \
  python \
  valgrind \
  zlib1g-dev

RUN cargo install cargo-watch

RUN echo "[workspace]\n\
  members = [\n\
  \"consumer\",\n\
  \"utils\"\n\
  ]" > ./Cargo.toml

COPY ./consumer/Cargo.toml ./consumer/Cargo.lock ./consumer/
COPY ./utils/Cargo.toml ./utils/

RUN mkdir consumer/src
RUN echo "fn main() {}" > ./consumer/src/main.rs

RUN mkdir utils/src
RUN echo "fn main() {}" > ./utils/src/main.rs

RUN cargo build

COPY ./consumer/src ./consumer/src
COPY ./utils/src ./utils/src

EXPOSE 8000

CMD ["cargo","watch","-x","run"]
