---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-container
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: 'myuser'
            - name: POSTGRES_PASSWORD
              value: 'mypassword'
            - name: POSTGRES_DB
              value: 'mydb'
          volumeMounts:
            - name: init-scripts-volume
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-scripts-volume
          hostPath:
            path: /Users/fabioferreira/Projects/rust-noob/db-init-scripts
            type: Directory
---

